### PR TITLE
Added NAMD 2.14 build instructions for ARCHER2

### PR DESCRIPTION
**Pull request by mbareford**

### CODE REVIEW

**Review by aturner-epcc — CHANGES_REQUESTED** [review]
Some stray instructions from elsewhere seem to have crept in. Are all the non-NAMD changes supposed to be in too?

**Comment by mbareford** [comment]
If you mean TCL and Charm++ then yes those components need to be built also. TCL version is specific to the NAMD version and the Charm++ version is bundled with the NAMD archive.

**Comment by aturner-epcc** [comment]
No, I meant the non-NAMD stuff that is in the PR, e.g.:

* readme.txt
* CMake
* gnu parallel
* mpi4py

The readme.txt definitely needs to be removed as it refers to previewing the ARCHER2 docs and website which are not relevant here.

**Comment by mbareford** [comment]
I've made a mistake here. Is it possible to remove those files not-relating to NAMD from the pull request? Or do I need to start again?

**Comment by aturner-epcc** [comment]
I think we need to cancel this PR and you should submit a new one. I will close the PR now.

**Pull request closed without merging**
